services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${NEON_DATABASE_URL}
      - DATABASE_USER=${NEON_DATABASE_USER}
      - DATABASE_PASSWORD=${NEON_DATABASE_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=${PUBLIC_URL}