services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://ep-lucky-smoke-a5g3zujx.us-east-2.aws.neon.tech/portal-egresso
      - DATABASE_USER=portal-egresso_owner
      - DATABASE_PASSWORD=bW86eYpNgVwJ
      - JWT_SECRET_KEY=rlMT7aEZSePCUiVpkMBZLr0vtrCPB6uuDNpKQ2AoHgMoUir/xm7PwvXlgqDmVLR4//+yADBCM9savCMKUCxaAw==

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8080  # Variável de ambiente para o Vite