package com.ufma.PortalEgresso.controller;

import com.ufma.PortalEgresso.exception.BuscaVaziaRunTime;
import com.ufma.PortalEgresso.exception.RegraNegocioRunTime;
import com.ufma.PortalEgresso.model.entity.*;
import com.ufma.PortalEgresso.model.entity.DTOs.*;
import com.ufma.PortalEgresso.service.CoordenadorService;
import com.ufma.PortalEgresso.service.CursoService;
import com.ufma.PortalEgresso.service.DepoimentoService;
import com.ufma.PortalEgresso.service.OportunidadeService;
import com.ufma.PortalEgresso.service.EgressoService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.UUID;

@RestController
@RequestMapping("/api/coordenador")
public class CoordenadorController {
    @Autowired
    CoordenadorService coordenadorService;
    @Autowired
    private EgressoService egressoService;
    @Autowired
    private CursoService cursoService;
    @Autowired
    private DepoimentoService depoimentoService;
    @Autowired
    private OportunidadeService oportunidadeService;

    // -------------------- AUTENTICAÇÃO ---------------------
    @PostMapping("/login")
    public ResponseEntity login(@RequestBody CoordenadorDTO request) {
        try {
            coordenadorService.efetuarLogin(request.getLogin(), request.getSenha());
            return ResponseEntity.ok().body(true);
        } catch (RegraNegocioRunTime e) {
            return ResponseEntity.badRequest().body(e.getMessage());
        }
    }

    @PostMapping("/cadastrarEgresso")
    public ResponseEntity cadastrarEgresso(@RequestBody EgressoDTO egressoRequest) {
        try {
            PasswordEncoder passwordEncoder = new BCryptPasswordEncoder();
            String senhaCodificada = passwordEncoder.encode(egressoRequest.getSenha());
            Egresso egresso = Egresso.builder()
                .nome(egressoRequest.getNome())
                .email(egressoRequest.getEmail())
                .foto("/9j/4AAQSkZJRgABAQACWAJYAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAPUA9QDASIAAhEBAxEB/8QAGwABAAIDAQEAAAAAAAAAAAAAAAQHAgUGAQP/xABIEAEAAQMCAQYKCAQDBQkAAAAAAQIDBAURBhMhMUFR0RIVU1VhcYGRkpMHFCIycqGxwSMkQlJDYqIzY4KywhYlNERUZIPS4f/EABYBAQEBAAAAAAAAAAAAAAAAAAABAv/EABYRAQEBAAAAAAAAAAAAAAAAAAARAf/aAAwDAQACEQMRAD8AyAaQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE/TtE1HVav5PFruU77Tcnmoj2zzOv076OeaK9RzP/jsR/wBU9yDgUnG07NzJ/lsS/e/BbmY963MLhjSMDabODamuP67keHV75bemmKaYiIiIjqgqqiscF69fjf6nFqP97cpp/JsLX0dapXH8TKxLfqmqr9lnbBRXdP0bZE/e1K1HqtT3sp+jW71apR7bM96whKK3r+jfNj7moY8/ioqjvQr3AOtW/ufVrv4bu36wtUWil8nhrWsXebum39o66KfDj8t2rroqt1eDXTNNUdVUbSvxHysHFzafBycazejsuURJRRQtPO4B0nKiZx4uYlf+7nen3S5PUuBtWwd68eKcy3Hkuar4Z/bcqOYGVy3XauVW7lFVFdPNNNUbTHsYqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9ooquV00UUzVVVO0UxG8zPod1w/wABTXFOTq+8R0xjRO0/8U/tAOV0rQ8/Wbvg4liZoidqrtXNRT65/aFgaRwJp+DFN3M/nL0c+1UbUR6qev2uos2LWPZptWbdFu3TG1NNMbRD6MqxoopooiimmKaYjaIiNohkAAAAAAAAAAABtAA1+p6Lp+r2/BzMai5PVX0VU+qelwetcBZeJ4V7Ta5yrUc/JzzXI9XVKzDYFB10VW66qK6Zpqpnaaao2mJeLj1zhnA1yiZu0cnkRH2b9HNVHr7Y9asNa4fztDveDk0eFaqnai9T92run0KjVgKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACTg4OTqOXRi4tqbl2voiOiI7ZnqhlpunZOq5tGLi0eFcq55meimOuZnqhbmhaBi6Fh8lap8K7Vz3Lsxz1z+0ehBD4d4UxtEt03a/BvZsx9q7Mc1Pop7PX0y6KI2BFAAAAAAAAAAAAAAAAAAHxycWzl2K7F+1RctVxtVRVG8S+wCreJ+D7uk+Fl4XhXcLpqjpqtevtj0+9yi/KqYqiYmImJ5tpVvxdwj9S8PUdOt/wAv967Zj/D9Mej9FwcWAqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD7YmJfzsq3jY1ua7tyrwaaYfFaXBvDnirD+t5NH85fp6J/w6f7fX2oNlw9w/j6FgcjTEV369pvXdvvT2R6IbkEUAAAAAAAAAAAAAAAAAAAAAAeVU01dMRPregKv4x4W8V3Zz8Oj+TuVfboj/AAqp/wCmfyckvm/Yt5Nmuzdoiu3XE01Uz0TEqe4k0K5oWpzajerHufas1z1x2T6YXEacBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB98PFu52ZZxbEb3btcU0wDp+BtB+v506hkUb4+NV9mJjmrr7o6fXss+I2Q9L0+1penWcO1H2LVO2/wDdPXPtlMZUAAAAAAAAAAAAAAAAAAAAAAAAAAarX9Gta1pVzFqiIufetV/21dXs6pbUBQ16zcx71yzdomi5bqmmqmeqYfN3P0gaLyd2jVrVO1NcxbvbdvVV7ej3OGVABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAd39Hmk+Hcvarcp5qf4Vnft/qn9ve4aiiq5cpt0RvXVMU0x2zPQu3R8CnS9Kx8Kjb+FRETMddXTM+/dNE4BFAAAAAAAAAAAAAAAAAAAAAAAAAAAARdQwreo4F/EvRvbu0TTPo7J9k86ksvGu4WXexr0bXLVc0VeuF7q0+kLTeQ1GzqFEbU5FPgV7f3098foYONAaQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0XBOBGdxJZqqjejGib1Xrjmj85/JbURs4n6OcPk9PysyY57tyKIn0Ux3z+Tt2dUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaLi7T/GHDeVRTG9y1HLUeunn/AE3b1jXTFVM0zG8TzTHoBQglajiTg6lk4s/4N2qiPVE835IrSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPYpmqYpjpnmBcXCeN9V4YwaNtpqt8pPrqnf926fHFtRYxbVmOi3RTT7o2fZlQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFT8d40Y/E92uI2i/bpue3baf0c07n6SLG2Tp+REfepron2TE/vLhlQAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEnTrfK6niW/7r9Ef6oRmw0KnwuINOj/3NH6guyOt6DKgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOJ+ke3vpmHc/tvzHvpnuVws76Rad+H7M9mTT+lSsVxABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT9Dq8HX9Oq7Mm3/zQgPvhXOSz8a5/Zdoq91UAvYeQ9ZUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAByH0i1baBYp7cmn/lqVisX6SLm2Bg29/vXqqvdT/+q6XEAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3mOeOmOcAXrgXoyMDHvx0XLdNXviEhoODMr61wth8+9VqJtT/AMM92zfsqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArj6R7/hZ+DjxP3LVVc+2dv2cS6DjXKjJ4pyoid4tRTaj2Rz/nMufaQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYH0cZu9vNwZnnpqi9THonmn9Id6pzhPUI07iPFuVVbW7k8lX6qub9dlxRO6ar0BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfO/dpsWa7tc7UUUzVVPoiN30c1xvqP1Lhy7bpna5kzFmn1Tz1flH5gqzKyKsvLvZNf3rtdVc+2d3yBpAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADnjonae1dHDmpxq2h4+VM73PB8C76K45p7/apd2HAGr/VdSr067Vtayeejfqrjvj9ITRZoCKAAAAAAAAAAAAAAAAAAAAAAAAAAAAKs481P65rcYtFW9rEjwJ/HPPV+0LC1zU6NI0i/mVbeFRG1FM/1VT0R71K3Lld27XcuVTVXXM1VTPXM9K4MQFQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZW7ldm7Tct1TTXRVFVNUdUx0SxAXRw/q9Gs6Tayo25T7t2mP6a46e/wBraqh4T12dF1OIu1fyl/am7/l7KvZ+i3aaorpiaZ3ieeJjrZV6AAAAAAAAAAAAAAAAAAAAAAAAAA8mdnrnuLdfjRtM2tVfzd7em1H9vbV7P1ByHHWt/XtSjAs172MWftTE81Vzr93R73JEzMzMzO8zzzM9Y0gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsHgfiXlKKNIy6/t0x/L1zP3o/t9cdSvmVFdVuumuiqaaqZ3iYnaYlBfY5fhLiijV8aMbKriM63HP/ALyP7o9PbDqEUAAAAAAAAAAAAAAAAAAAAAAB8sjJs4liu/fuRbtUR4VVdXREA+OpahY0vBuZeTX4Nu3G/N0zPVEemVN6vql/WdRuZl+eermpo6qKeqIT+JuIruu5v2Jqow7c/wAKiev/ADT6Z/JolQAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfSzfu41+i/ZuVUXaJ8KmqmeeJWnwvxXa1m3GPkzTbzqY56eq5HbT3KoZUV1266a6Kpprpnemqmdpie2EF9jiOGuN6MnwMPVa6bd/oovzzU1/i7J9PQ7aJiehFegAAAAAAAAAAAAAAAAAA1+razh6Pizfy7vgx0U0Rz1Vz2RAJWVlWMPHrv5Fym3aojequqeaFVcT8UXtcu8ja8K3g0TvTRPTXP91X7R1Iuv8R5evZG93+Hj0T/AA7NM80eme2WnWAAqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADpeH+MczR/BsX98nDjm8GZ+1RH+Wf2lzQC7tL1jC1exy2HfpuR/VT0VU+uOpPUPjZN/Ev038a9Xau09FdE7S7XSPpDuURTa1Wz4cdHL2o5/bT3MxVhiHgarg6na5TDybd6OuKZ549cdMJm4AAAAAAAAAAAPJqiImZmIiOmZ6gevJmIiZmdohzercbaXpszbs1/W70c3gWZ5o9dXR7t3BazxTqWs70XbvJY8/4NrmifXPTIOy13jnFwYrsafNOVkdE1/4dE+vr9nvV1m52TqOTVk5d6q7dq66uqOyI6oRxUAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGdq7csXYuWrldu5HRVRO0x7YdJp/Her4e1N+qjLojysbVfFH7uYAWdhfSFpd/aMq3exau2Y8On3xz/k6DE1rTM6InGz8e5M9UVxv7p51IiRV+b7vd47VF2NRzsX/YZmRa/BdmGwtcWa7a+7qV6fxxFX6wQXIKkp441+mP/F26vXZpZf8AbrXv/UWvk0kFs7m6oK+M9fr/APPeD+G3TH7Id7iDWL8bXNTypjsi5MfoQXPdyLNinwr12i3T211RH6tLmcY6Hh7xObTdqj+mzE1z745lRXLld2rwrldVc9tczP6sSDvM/wCkeuYmnAwYp/z36t/9Md7lNR13U9VmYy8u5XR5On7NHuhrgQAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIjwp2p557I5wBJt6fm3Y3t4eRX+G1VP7PrGjap5ty/k1dwIIneJdU83Zfyau48S6p5uy/k1dwIIneJdU83Zfyau48S6p5uy/k1dwIIneJdU83Zfyau48S6p5uy/k1dwIIneJdU83Zfyau48S6p5uy/k1dwIIneJdU83Zfyau48S6p5uy/k1dwIIneJdU83Zfyau48S6p5uy/k1dwIIneJdU83Zfyau48S6p5uy/k1dwIIneJdU83Zfyau48S6p5uy/k1dwIIneJdU83Zfyau48S6p5uy/k1dwIIneJdU83Zfyau48S6p5uy/k1dwIIneJdU83Zfyau48S6p5uy/k1dwIIneJdU83Zfyau48S6p5uy/k1dwIIneJdU83Zfyau48S6p5uy/k1dwIIneJdU83Zfyau48S6p5uy/k1dwIIneJdU83Zfyau48S6p5uy/k1dwIIneJdU83Zfyau48S6p5uy/k1dwIIneJdU83Zfyau48S6p5uy/k1dwIIneJdU83Zfyau48S6p5uy/k1dwIIneJdU83Zfyau48S6p5uy/k1dwIIneJdU825fyau5jVpGpU/e0/Lj12au4EMfS5YvWv9pauUfiomP1fOOfoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH2xcS/m5FNjGtV3btXRRRG8u80TgC1R4N3Vq+Ur6eQtz9mPXPX7EHEYOmZup3eTwsa5eq65pjmj1z0Q6zT/o6yLm1WoZdNqPJ2Y8KffPN+qwcfGs4tqm1Yt0W7dPRTRTERD6lVz2HwVoeJtP1Tl6o/qv1TV+XQ3VjCxsaNrGPatx2UURH6PuIPNnoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAxqopqjaqImOyY3a/K4f0nMifrGn49c/wB0URTPvhsgHG530eaddiasO/exquyZ8On8+f8ANympcGaxp0TXFmMm1H9djnmPXT0rdCig5iYmYmNpjmmOx4uTV+GNN1imar9nwL23NetxtVHr7farnXOE8/Rd7u3L4nlqI+7+KOr9FqNCAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANtofD+ZruT4FiPAs0z/EvVR9mnvn0Ppw5w9e17M8GJmjFtz/ABbu3R6I9K2sLBx9PxrePi24t2qI2imP19MpRF0fQ8LRcaLeJb+1MfbuVc9Vc+mf2bMEUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeVUxVTNMxExPNMS9AcJxLwPTcivL0iiKbnTXjRzRV+Hsn0K+qpqoqmmqJpqidpiY2mJX5Mbxs5HizhKjU7dWbhUxTm0xvVTHNF2P/ALelaKwHtVM0VTTVExVE7TExtMS8VAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABO0jS7+sajbxLHNNXPVXtzUU9cyg9PRG62+EdCjRtMiq7Ttl34iq7v009lPs/VBt9N07H0vBtYuNT4NuiPbVPXM+mUsEUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwfHHDUV0V6tiUfxKY3yKKY+9H9/rjrV8vyqIqpmJiJiY22lUPFehTouqzFqmfqt/eu16O2n2fpsuDQgKgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADpuCdH8ZazGRdp3sYu1c7xzVV/0x+/sWtHQ0PB+m+LeH7EVU7Xr8ctc9c9EeyNm/ZUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAabifSI1nRrtimI5aj+JZn/NHV7ehuSegFBTExO0xMT2SOg4y03xdxDemina1kRy1Ht+9Hv397n2kAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE7R8LxjrGJidV27EVfh6Z/KJQXV/R/i8txBXemOaxZmY9c836bgtGmIimIiNo25npHQMqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA436RMGLuk2MymPtY9zafw1c36xCtF1cQYn13QM6x11Wapj1xzx+ild943XAAVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYH0a2Y5PUb23PNVFH5TP7q/WV9HFMeJ8urtyNv9MJo7MBFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeV0xXRNM9ExtKhr1vkr9y3/ZXNPunZfSjdVpinWM2mOrIuR/qlcEQBUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFk/RxVvpOZT2ZG/vphWzvvo1vR/wB42Ov7FcfnCaO/ARQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABRuqVeHq2bVHXkXJ/1Su+5XFu1XXPRTEzPsUPcr5S7Xcn+qqavfO64MQFQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdRwDlchxHyUztGRZqoj1xzx+kuXStOy5wNSxsunps3Ka/Zvz/luC846BjbuU3KKa6J3pqiJie2JZMqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1HE2X9S4dz72+08jNFPrq5o/VTKxvpGz4owMXBpn7V2vlKo/y09H5z+SuVwAFQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABa/A+p/X9BotV1b3cX+FV6v6Z93N7HTKf4S1jxPrdFVyrbHv7WrvZHZPsn91vxO/Xzsq9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeT0PXO8Yaz4q0WuLde2Rkfw7XbHbV7I/OYBXvFOpeNNfyL1NW9q3PJW/w09ftneWmBpAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABaHBGvxqOD9SyK/5rGp2jfpro6p9cdE+xV6Rg5t/Ts21l41fg3bVW8T29sT6EF6jWaHrNjWtPoybM7VR9m5b66KuzubNFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeTIML963Ys3Lt2uKKKKZqqqnoiI61N8Q6zXreq15E7xZp+xZonqp756W/424ljMuVaXh3N7FE/wAaumfv1R/THoj85cWuAAqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANho2sZOi59OTjzvE81y3M81dPZK3dI1fF1nCpycaveOiuifvUT2SpJM0zVMvScuMnEu+BX0VUzz01x2THXCaLxGg4f4pwtboptxMWcuI+1Zqnp9NM9cfm3+6KAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+WRk2cWxXev3aLduiN6qq52iAfSZcFxdxftFenabc3q+7ev0z0dtNM9vbKDxLxrcz/DxNNmq1jTzV3eiq5Ho7I/Nxy4ACoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9pqqoqiqmqaaoneJidpiXY6Jx7k4ng2dTonJtRzRdp/2kev+79XGgLv07V8HVbfKYeTRdjrpidqqfXHTCcoS3duWbkXLVdVFdPRVTO0x7XS6fx1q+HtTeqoy6I6rsbVfFH7pFWsOOw/pE027ERlY9/Hq7Yjw6fy5/ybnH4p0TJ25PUseJnqrq8CfzQbgR7ediXY3oyrFX4bkT+768tan/Eo+KAZjDlrflKPig5a35Sj4oBmMOWt+Uo+KDlrflKPigGYw5a35Sj4oOWt+Uo+KAZjDlrflKPig5a35Sj4oBmMOWt+Uo+KDlrflKPigGYw5a35Sj4oOWt+Uo+KAZjDlrflKPig5a35Sj4oBmMOWt+Uo+KDlrflKPigGYw5a35Sj4oOWt+Uo+KAZjDlrflKPig5a35Sj4oBmMOWt+Uo+KDlrflKPigGYw5a35Sj4oOWt+Uo+KAZjDlrflKPig5a35Sj4oBmMOWt+Uo+KDlrflKPigGYw5a35Sj4oOWt+Uo+KAZjDlrflKPig5a35Sj4oBmMOWt+Uo+KDlrflKPigGYw5a35Sj4oOWt+Uo+KAZjDlrflKPig5a35Sj4oBmMOWt+Uo+KGNWRYp+9etx66oB9RAva1pmPEzd1DFo27bsNXk8caHj/dyar9XZZtzP5ztAOjeVVRTTNUzERHPMz1K+z/AKR7tUTTgYNNH+e/Vv8AlHe5XUdd1LVZ2zMuuujycfZp90EFhaxxzp2BFVrGn65f6Nrc/Yj11dyvdW1zP1m74eXemaIn7Nqnmop9Ufu1wsQAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANo7I9xuAG5uCBubgBubgBubgBubgBubgBubgBubgBubgBubgBubgBubgBubgBubgBubgBubgBubgBubgBubgBudIKG0R0RAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/9k=")
                .senha(senhaCodificada)
                .build();

            Egresso cadastrado = coordenadorService.cadastrarEgresso(egresso);

            return ResponseEntity.ok().body(cadastrado);
        } catch (RegraNegocioRunTime e) {
            return ResponseEntity.badRequest().body(e.getMessage());
        }
    }

    // -------------------- RESPONSABILIDADES ---------------------

    @PostMapping("/cadastrarCurso/{id}")
    public ResponseEntity cadastrarCurso(@PathVariable UUID id, @RequestBody CursoDTO cursoRequest) {
        try {
            Coordenador coordenador = coordenadorService.buscarPorId(id).get();
            coordenadorService.cadastrarCurso(
                    coordenador.getLogin(),
                    cursoRequest.getNome(),
                    cursoRequest.getNivel());

            return ResponseEntity.ok().body(true);
        } catch (RegraNegocioRunTime e) {
            return ResponseEntity.badRequest().body(e.getMessage());
        }
    }

    @PostMapping("/associarCursoAEgresso/{idEgresso}/{idCurso}")
    public ResponseEntity associarCursoAEgresso(
            @PathVariable UUID idEgresso,
            @PathVariable UUID idCurso,
            @RequestBody CursoEgressoDTO cursoEgressoRequest) {

        try {
            Egresso egresso = egressoService.buscarPorId(idEgresso).get();
            Curso curso = cursoService.buscarPorId(idCurso).get();

            Curso cursoAtualizado = coordenadorService.associarCursoAEgresso(egresso, curso, cursoEgressoRequest.getAnoInicio(), cursoEgressoRequest.getAnoFim());
            return ResponseEntity.ok().body(cursoAtualizado);
        } catch (RegraNegocioRunTime e) {
            return ResponseEntity.badRequest().body("Não foi possível associar curso a egresso");
        }
    }

    @PostMapping("/homologarDepoimento/{id}")
    public ResponseEntity homologarDepoimento(@PathVariable UUID id, @RequestBody DepoimentoDTO depoimentoRequest) {
        try {
            Depoimento depoimento = depoimentoService.buscarPorId(id).get();
            Depoimento salvo = coordenadorService.homologarDepoimento(depoimento, depoimentoRequest.getStatus());

            return ResponseEntity.ok().body(salvo);
        } catch (RegraNegocioRunTime e) {
            return ResponseEntity.badRequest().body(e.getMessage());
        }
    }

    @PostMapping("/homologarOportunidade/{id}")
    public ResponseEntity homologarOportunidade(@PathVariable UUID id, @RequestBody OportunidadeDTO oportunidadeRequest) {
        try {
            Oportunidade oportunidade = oportunidadeService.buscarPorId(id).get();
            Oportunidade salvo = coordenadorService.homologarOportunidade(oportunidade, oportunidadeRequest.getStatus());

            return ResponseEntity.ok().body(salvo);
        } catch (RegraNegocioRunTime e) {
            return ResponseEntity.badRequest().body(e.getMessage());
        }
    }

    // -------------------- endpoints CRUD ---------------------

    @PostMapping("/salvar")
    public ResponseEntity salvar(@RequestBody CoordenadorDTO request) {
        PasswordEncoder passwordEncoder = new BCryptPasswordEncoder();
        String senhaCodificada = passwordEncoder.encode(request.getSenha());
        Coordenador coordenador = Coordenador.builder()
                .login(request.getLogin())
                .senha(senhaCodificada)
                .build();
        try {
            Coordenador salvo = coordenadorService.salvar(coordenador);
            return new ResponseEntity<>(salvo, HttpStatus.CREATED);
        } catch (RegraNegocioRunTime e) {
            return ResponseEntity.badRequest().body(e.getMessage());
        }
    }

    @PutMapping("{id}")
    public ResponseEntity atualizar(@PathVariable UUID id, @RequestBody CoordenadorDTO request) {
        try {
            // Recupera o coordenador existente do banco de dados
            Coordenador coordenadorExistente = coordenadorService.buscarPorId(id).get();

            if (coordenadorExistente == null) {
                return ResponseEntity.notFound().build(); // Retorna 404 se o coordenador não for encontrado
            }

            // Atualiza os campos passados no DTO
            if (request.getLogin() != null && !request.getLogin().trim().isEmpty()) {
                coordenadorExistente.setLogin(request.getLogin());
            }
            if (request.getSenha() != null && !request.getSenha().trim().isEmpty()) {
                PasswordEncoder passwordEncoder = new BCryptPasswordEncoder();
                String senhaCodificada = passwordEncoder.encode(request.getSenha());
                coordenadorExistente.setSenha(senhaCodificada);
            }

            // Atualiza o coordenador no banco de dados
            Coordenador atualizado = coordenadorService.atualizar(coordenadorExistente);

            return ResponseEntity.ok(atualizado);
        } catch (RegraNegocioRunTime e) {
            return ResponseEntity.badRequest().body(e.getMessage());
        }
    }

    @GetMapping("/buscarPorId/{id}")
    public ResponseEntity buscarPorId(@PathVariable UUID id) {
        try {
            Coordenador coordenador = coordenadorService.buscarPorId(id).get();
            return ResponseEntity.ok(coordenador);

        } catch (RegraNegocioRunTime e) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body(e.getMessage());
        }
    }

    @GetMapping("/listarTodos")
    public ResponseEntity listarTodos() {
        try {
            List<Coordenador> lista = coordenadorService.listarTodos();
            return ResponseEntity.ok(lista);

        } catch (RegraNegocioRunTime | BuscaVaziaRunTime e) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body(e.getMessage());
        }
    }

    @DeleteMapping("{id}")
    public ResponseEntity deletar(@PathVariable UUID id){
        try {
            coordenadorService.deletar(id);
            return ResponseEntity.status(HttpStatus.NO_CONTENT).build();
        } catch (RegraNegocioRunTime e) {
            return ResponseEntity.badRequest().body(e.getMessage());
        }
    }

}
